### ISSUE TITLE
Unable to 'skip' records

### ISSUE THREAD

**Issue by igorgeyn** [frankfarach/npi#21]
Hi Frank -- this is a fantastic project. Thank you very much for making it available.
I am having a hard time using the skip field (I need it to build out a list of all the providers in D.C. -- not just the first 200.
Creating the first df works fine. It's only from the second one on that I am having issues. Thanks!

``` r
dc_200 <- npi_search(city = "Washington",
                     state = "DC",
                     limit = 200)

dc_400 <- npi_search(city = "Washington",
                     state = "DC",
                     limit = 200,
                     skip = 200)
#> Error in npi_search(city = "Washington", state = "DC", limit = 200, skip = 200) : unused argument (skip = 200)

dc_600 <- npi_search(city = "Washington",
                     state = "DC",
                     limit = 200,
                     skip = 400)
#> Error in npi_search(city = "Washington", state = "DC", limit = 200, skip = 400) : unused argument (skip = 400)

dc_800 <- npi_search(city = "Washington",
                     state = "DC",
                     limit = 200,
                     skip = 600)
#> Error in npi_search(city = "Washington", state = "DC", limit = 200, skip = 600) : unused argument (skip = 600)
```

**Comment by frankfarach** [comment]
Hi Igor - thanks for the feedback and for opening this issue. Although `skip` is part of the NPPES API, the `npi` package does some higher-level wrapping for the user with the `limit` parameter. See if this does what you want:

`dc_1200 <- npi_search(city = "Washington", state = "DC", limit = 1200)`

This should execute up to 5 API calls, auto-incrementing the API's `skip` parameter for you behind the scenes, and stopping when either fewer than 200 records are returned, or the total API limit of 1200 records has been reached. It should return a single data frame with all of the results combined.

The help for `npi_search()` mentions this [documented parameter](https://github.com/frankfarach/npi/blob/30c3a30240ae3af513431ed67f0755683a36adee/R/npi_search.R#L74), but it probably deserves a little more explanation by example.

`limit: Maximum number of records to return, from 1 to 1200 inclusive. The default is 10. Because the API returns up to 200 records per request, values of limit greater than 200 will result in multiple API calls.`

Let me know how this goes. I will also try to document this better by providing an example and explaining the logic in the README before closing out this issue.

Thanks, again, for helping to improve the quality of this package.

**Comment by igorgeyn** [comment]
@frankfarach -- thanks so much. That does exactly what I wanted.  Very much appreciate the thorough walkthrough and directions to other resources!

**Comment by frankfarach** [comment]
Happy to hear it, @igorgeyn. Thank you again for raising this issue.
