### ISSUE TITLE
npiShiny app/package idea

### ISSUE THREAD

**Issue by parmsam** [frankfarach/npi#37]
Had an idea for a shiny app for enhanced search of NPI records. Began working on it [here](https://github.com/parmsam/npiShiny) recently. Idea would be to improve upon what is [already available](https://npiregistry.cms.hhs.gov/) (maybe allowing multiple term searches at once) using the [golem package](https://thinkr-open.github.io/golem/) and npi package.

**Comment by frankfarach** [comment]
That could be an interesting application for npi. I think it would be helpful to write out some concrete use cases. Do you have any thoughts?

**Comment by parmsam** [comment]
Yeah, that's a good point. It seems that many healthcare organizations repeatedly search for NPI data linked to individuals or organizations. One limitation of the CMS search tool is that it can only do one keyword set or pattern search at a time. I imagine there may be a need to have an app to search many individuals at once or other search terms at once (in bulk). `npi::npi_search()` combined with [`purrr functions`](https://purrr.tidyverse.org/) could be used to generate output for multiple search queries. This capacity could be provided in a Shiny app for non-programmers to use.

**Comment by frankfarach** [comment]
@parmsam I'm closing this issue for now since `npiShiny` is another package that would depend on this one, and the ideas about `purrr` with `npi` are covered in other issues. I look forward to seeing how the Shiny app progresses and am open to ideas for improving the `npi` package to make it easier to use in other applications.
